# Generated by Django 3.2.7 on 2021-09-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magiccity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='bizz_name',
        ),
    ]
