# Generated by Django 3.2.7 on 2021-09-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magiccity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
    ]
