# Generated by Django 3.2.7 on 2021-10-30 19:21

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magiccity', '0002_alter_post_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='house_image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
