# Generated by Django 3.2.7 on 2021-09-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magiccity', '0003_auto_20210928_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
