# Generated by Django 3.2.7 on 2021-09-30 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magiccity', '0004_auto_20210928_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='description',
            new_name='house_description',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='location',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
